const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./src/modules/routes/routes.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "hospital",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:8080",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "routes",
    },
    {
      name: "Appointment",
      description: "routes 2",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header",
    },
    petstore_auth: {
      type: "oauth2",
      authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
      flow: "implicit",
      scopes: {
        read_pets: "read your pets",
        write_pets: "modify pets in your account",
      },
    },
  },
  definitions: {
    Appointment: {
      name: "Nastya",
      docName: "Vasya",
      date: "2021-12-02",
      complaints: "vse ploho",
    },
    AppointmentPatch: {
      _id: "xbvdb32sfbfg7fgbs",
      name: "Nastya",
      docName: "Vasya",
      date: "2021-12-02",
      complaints: "vse ploho",
    },
    GetAppointments: {
      $rowsOnPage: "5",
      $currentPage: "1",
      value: "docName",
      direction: "asc",
      before: "0000-00-00",
      after: "9999-99-99",
    },
    AddUser: {
      $login: "Olesya",
      $password: "1111fdfv21w32dfz",
    },
    AddFile: {
      $img: Object,
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./app.js");
});
